// AUTO-GENERATED — do not edit manually. Regenerate via build script.

export const handlerLoaders: Record<string, () => Promise<{ default?: unknown; handler?: unknown }>> = {
  // 2026-05-16: 'adapt-viral-reel' removido junto com Reels Viral (saiu do KAI).
  'analyze-client-onboarding': () => import('./_handlers/analyze-client-onboarding.js'),
  'analyze-image-complete': () => import('./_handlers/analyze-image-complete.js'),
  'analyze-style': () => import('./_handlers/analyze-style.js'),
  'analyze-youtube-sentiment': () => import('./_handlers/analyze-youtube-sentiment.js'),
  'batch-sync-posts': () => import('./_handlers/batch-sync-posts.js'),
  'batch-transcribe-posts': () => import('./_handlers/batch-transcribe-posts.js'),
  'client-add-source': () => import('./_handlers/client-add-source.js'),
  'client-context': () => import('./_handlers/client-context.js'),
  'client-social-status': () => import('./_handlers/client-social-status.js'),
  'cron-approval-tokens-cleanup': () => import('./_handlers/cron-approval-tokens-cleanup.js'),
  'cron-generate-daily-brief': () => import('./_handlers/cron-generate-daily-brief.js'),
  // 2026-05-18 rev2 — cron-fetch-published-metrics arquivado (dependia de Metricool).
  // Wave A vai reimplementar via late-analytics quando entregar Performance UI.
  // 2026-05-16: 'cron-radar-master' removido junto com Radar Viral (saiu do KAI).
  'cron-scrape-instagram': () => import('./_handlers/cron-scrape-instagram.js'),
  'cron-scrape-linkedin': () => import('./_handlers/cron-scrape-linkedin.js'),
  'cron-scrape-news': () => import('./_handlers/cron-scrape-news.js'),
  'cron-scrape-threads': () => import('./_handlers/cron-scrape-threads.js'),
  'cron-scrape-tiktok': () => import('./_handlers/cron-scrape-tiktok.js'),
  'cron-scrape-twitter': () => import('./_handlers/cron-scrape-twitter.js'),
  'cron-transcribe-recent-posts': () => import('./_handlers/cron-transcribe-recent-posts.js'),
  'delete-account': () => import('./_handlers/delete-account.js'),
  'embed-client-content': () => import('./_handlers/embed-client-content.js'),
  'embed-knowledge': () => import('./_handlers/embed-knowledge.js'),
  'email-welcome': () => import('./_handlers/email-welcome.js'),
  'extract-branding': () => import('./_handlers/extract-branding.js'),
  'feedback-carousel': () => import('./_handlers/feedback-carousel.js'),
  'referrals-track': () => import('./_handlers/referrals-track.js'),
  'extract-docx': () => import('./_handlers/extract-docx.js'),
  'extract-instagram': () => import('./_handlers/extract-instagram.js'),
  'extract-knowledge': () => import('./_handlers/extract-knowledge.js'),
  'extract-pdf': () => import('./_handlers/extract-pdf.js'),
  'extract-youtube': () => import('./_handlers/extract-youtube.js'),
  'fetch-beehiiv-metrics': () => import('./_handlers/fetch-beehiiv-metrics.js'),
  'fetch-instagram-metrics': () => import('./_handlers/fetch-instagram-metrics.js'),
  'fetch-linkedin-apify': () => import('./_handlers/fetch-linkedin-apify.js'),
  'fetch-linkedin-posts-apify': () => import('./_handlers/fetch-linkedin-posts-apify.js'),
  'fetch-reference-content': () => import('./_handlers/fetch-reference-content.js'),
  'fetch-rss-feed': () => import('./_handlers/fetch-rss-feed.js'),
  'fetch-tiktok-apify': () => import('./_handlers/fetch-tiktok-apify.js'),
  'fetch-twitter-apify': () => import('./_handlers/fetch-twitter-apify.js'),
  'fetch-youtube-apify': () => import('./_handlers/fetch-youtube-apify.js'),
  'fetch-youtube-metrics': () => import('./_handlers/fetch-youtube-metrics.js'),
  'fetch-late-metrics': () => import('./_handlers/fetch-late-metrics.js'),
  'firecrawl-scrape': () => import('./_handlers/firecrawl-scrape.js'),
  'generate-caption': () => import('./_handlers/generate-caption.js'),
  'generate-client-context': () => import('./_handlers/generate-client-context.js'),
  'generate-concepts': () => import('./_handlers/generate-concepts.js'),
  'generate-content-guidelines': () => import('./_handlers/generate-content-guidelines.js'),
  'generate-content-learnings': () => import('./_handlers/generate-content-learnings.js'),
  'generate-content-v2': () => import('./_handlers/generate-content-v2.js'),
  'generate-image': () => import('./_handlers/generate-image.js'),
  'generate-interview': () => import('./_handlers/generate-interview.js'),
  'generate-performance-insights': () => import('./_handlers/generate-performance-insights.js'),
  // 2026-05-16: 'generate-radar-brief' removido junto com Radar Viral (saiu do KAI).
  'generate-viral-carousel': () => import('./_handlers/generate-viral-carousel.js'),
  'generate-voice-profile': () => import('./_handlers/generate-voice-profile.js'),
  'get-vapid-public-key': () => import('./_handlers/get-vapid-public-key.js'),
  'get-integrations-status': () => import('./_handlers/get-integrations-status.js'),
  'google-news-search': () => import('./_handlers/google-news-search.js'),
  'google-trends-br': () => import('./_handlers/google-trends-br.js'),
  'image-search': () => import('./_handlers/image-search.js'),
  'import-clickup': () => import('./_handlers/import-clickup.js'),
  'instagram-search': () => import('./_handlers/instagram-search.js'),
  'kai-chat-stream': () => import('./_handlers/kai-chat-stream.js'),
  'kai-content-agent': () => import('./_handlers/kai-content-agent.js'),
  'kai-metrics-agent': () => import('./_handlers/kai-metrics-agent.js'),
  'kai-planning-agent': () => import('./_handlers/kai-planning-agent.js'),
  'kai-simple-chat': () => import('./_handlers/kai-simple-chat.js'),
  // 2026-05-18 rev2 — Metricool REMOVIDO. Late/Zernio é o publisher único.
  // 22 handlers metricool-* + 3 cron-metricool-* arquivados em
  // _TRASH-2026-05-18-metricool-removed/handlers/.
  // Late.ai/Zernio integration (publisher único pós-decisão Gabriel 2026-05-18).
  // Metricool removido (custo + falta WhatsApp + falta API create brand).
  'late-analytics': () => import('./_handlers/late-analytics.js'),
  'late-create-brand': () => import('./_handlers/late-create-brand.js'),
  'late-disconnect-account': () => import('./_handlers/late-disconnect-account.js'),
  'late-inbox': () => import('./_handlers/late-inbox.js'),
  'late-oauth-callback': () => import('./_handlers/late-oauth-callback.js'),
  'late-oauth-start': () => import('./_handlers/late-oauth-start.js'),
  'late-post': () => import('./_handlers/late-post.js'),
  'late-verify-accounts': () => import('./_handlers/late-verify-accounts.js'),
  'late-webhook': () => import('./_handlers/late-webhook.js'),
  'late-webhook-reprocess': () => import('./_handlers/late-webhook-reprocess.js'),
  'late-webhook-test': () => import('./_handlers/late-webhook-test.js'),
  'linkedin-oauth-callback': () => import('./_handlers/linkedin-oauth-callback.js'),
  'linkedin-oauth-start': () => import('./_handlers/linkedin-oauth-start.js'),
  'linkedin-post': () => import('./_handlers/linkedin-post.js'),
  'mcp-reader': () => import('./_handlers/mcp-reader.js'),
  // MCP server full (2026-05-16) — auto-discovery de TODAS as tools registradas.
  'mcp': () => import('./_handlers/mcp.js'),
  'mcp-tools-list': () => import('./_handlers/mcp-tools-list.js'),
  'mcp-tools-call': () => import('./_handlers/mcp-tools-call.js'),
  'mcp-resources-list': () => import('./_handlers/mcp-resources-list.js'),
  'mcp-resources-read': () => import('./_handlers/mcp-resources-read.js'),
  'process-automations': () => import('./_handlers/process-automations.js'),
  'process-due-date-notifications': () => import('./_handlers/process-due-date-notifications.js'),
  'process-email-notifications': () => import('./_handlers/process-email-notifications.js'),
  'process-knowledge': () => import('./_handlers/process-knowledge.js'),
  'process-push-queue': () => import('./_handlers/process-push-queue.js'),
  'process-recurring-content': () => import('./_handlers/process-recurring-content.js'),
  'process-scheduled-posts': () => import('./_handlers/process-scheduled-posts.js'),
  'publish-viral-carousel': () => import('./_handlers/publish-viral-carousel.js'),
  // 2026-05-16: handlers radar-* removidos junto com Radar Viral (saiu do KAI).
  // Mantido só radar-img-proxy porque é usado pelo Performance v2 pra IG CDN.
  'radar-img-proxy': () => import('./_handlers/radar-img-proxy.js'),
  'research-newsletter-topic': () => import('./_handlers/research-newsletter-topic.js'),
  'resolve-youtube-channel': () => import('./_handlers/resolve-youtube-channel.js'),
  'reverse-engineer': () => import('./_handlers/reverse-engineer.js'),
  'save-as-planning-item': () => import('./_handlers/save-as-planning-item.js'),
  'import-client-social-content': () => import('./_handlers/import-client-social-content.js'),
  'run-madureira-workflows-daily': () => import('./_handlers/run-madureira-workflows-daily.js'),
  'generate': () => import('./_handlers/generate.js'),
  'sync-profile': () => import('./_handlers/sync-profile.js'),
  'data-saved': () => import('./_handlers/data-saved.js'),
  'data-newsletters': () => import('./_handlers/data-newsletters.js'),
  'team-tasks-create': () => import('./_handlers/team-tasks-create.js'),
  // WRITE/DELETE handlers (2026-05-16) usados pelas tools edit*/delete* do KAI Chat
  'team-tasks-update': () => import('./_handlers/team-tasks-update.js'),
  'team-tasks-delete': () => import('./_handlers/team-tasks-delete.js'),
  'planning-items-delete': () => import('./_handlers/planning-items-delete.js'),
  // Observability — rate-limit dashboard (2026-05-17, Onda 3)
  'rate-limit-stats': () => import('./_handlers/rate-limit-stats.js'),
  // Histórico de eval runs (2026-05-17, Onda 11)
  'eval-history': () => import('./_handlers/eval-history.js'),
  // P0 handlers (2026-05-17) — substituem supabase.from().insert/update/delete
  // direto que existia nos hooks. Audit Backend Consistency identificou 11+
  // hooks bypassando assertClientAccess via PostgREST/Data API.
  'client-delete': () => import('./_handlers/client-delete.js'),
  'client-document-create': () => import('./_handlers/client-document-create.js'),
  'content-feedback-create': () => import('./_handlers/content-feedback-create.js'),
  'import-history-create': () => import('./_handlers/import-history-create.js'),
  'kanban-columns-create': () => import('./_handlers/kanban-columns-create.js'),
  'kanban-columns-update': () => import('./_handlers/kanban-columns-update.js'),
  'kanban-columns-delete': () => import('./_handlers/kanban-columns-delete.js'),
  'kanban-columns-init': () => import('./_handlers/kanban-columns-init.js'),
  'planning-items-create': () => import('./_handlers/planning-items-create.js'),
  'planning-items-update': () => import('./_handlers/planning-items-update.js'),
  'planning-items-reorder': () => import('./_handlers/planning-items-reorder.js'),
  'planning-comments-create': () => import('./_handlers/planning-comments-create.js'),
  'planning-comments-list': () => import('./_handlers/planning-comments-list.js'),
  'planning-comments-delete': () => import('./_handlers/planning-comments-delete.js'),
  'task-checklist-create': () => import('./_handlers/task-checklist-create.js'),
  'task-checklist-update': () => import('./_handlers/task-checklist-update.js'),
  'task-checklist-delete': () => import('./_handlers/task-checklist-delete.js'),
  'task-comments-create': () => import('./_handlers/task-comments-create.js'),
  'task-comments-delete': () => import('./_handlers/task-comments-delete.js'),
  'automations-delete': () => import('./_handlers/automations-delete.js'),
  'workspace-members-add': () => import('./_handlers/workspace-members-add.js'),
  'workspace-members-remove': () => import('./_handlers/workspace-members-remove.js'),
  'workspace-members-update-role': () => import('./_handlers/workspace-members-update-role.js'),
  'reference-update': () => import('./_handlers/reference-update.js'),
  'reference-delete': () => import('./_handlers/reference-delete.js'),
  'client-settings-update': () => import('./_handlers/client-settings-update.js'),
  'save-to-library': () => import('./_handlers/save-to-library.js'),
  'automations-create': () => import('./_handlers/automations-create.js'),
  'automations-list': () => import('./_handlers/automations-list.js'),
  'automations-toggle': () => import('./_handlers/automations-toggle.js'),
  // 2026-05-17: 'automation-webhook' removido (handler nunca existiu como arquivo).
  'ai-workflow-update': () => import('./_handlers/ai-workflow-update.js'),
  'ai-workflow-trigger': () => import('./_handlers/ai-workflow-trigger.js'),
  'ai-agent-update': () => import('./_handlers/ai-agent-update.js'),
  'client-update': () => import('./_handlers/client-update.js'),
  'client-create': () => import('./_handlers/client-create.js'),
  'upload': () => import('./_handlers/upload.js'),
  'upload-presign': () => import('./_handlers/upload-presign.js'),
  'img-proxy': () => import('./_handlers/img-proxy.js'),
  'profile-scraper': () => import('./_handlers/profile-scraper.js'),
  'brand-analysis': () => import('./_handlers/brand-analysis.js'),
  'voice-ingest': () => import('./_handlers/voice-ingest.js'),
  'images': () => import('./_handlers/images.js'),
  'transcribe-video': () => import('./_handlers/transcribe-video.js'),
  'dev-test-flows': () => import('./_handlers/dev-test-flows.js'),
  'scrape-newsletter': () => import('./_handlers/scrape-newsletter.js'),
  'scrape-website': () => import('./_handlers/scrape-website.js'),
  'search-knowledge': () => import('./_handlers/search-knowledge.js'),
  'send-invite-email': () => import('./_handlers/send-invite-email.js'),
  'send-publish-reminders': () => import('./_handlers/send-publish-reminders.js'),
  'send-push-notification': () => import('./_handlers/send-push-notification.js'),
  'stripe-create-checkout': () => import('./_handlers/stripe-create-checkout.js'),
  'stripe-portal': () => import('./_handlers/stripe-portal.js'),
  'stripe-webhook': () => import('./_handlers/stripe-webhook.js'),
  'sync-all-metrics': () => import('./_handlers/sync-all-metrics.js'),
  'sync-rss-to-library': () => import('./_handlers/sync-rss-to-library.js'),
  'telegram-daily-report': () => import('./_handlers/telegram-daily-report.js'),
  'telegram-notify': () => import('./_handlers/telegram-notify.js'),
  'telegram-poll': () => import('./_handlers/telegram-poll.js'),
  'telegram-send-notification': () => import('./_handlers/telegram-send-notification.js'),
  'transcribe-images': () => import('./_handlers/transcribe-images.js'),
  'transcribe-media': () => import('./_handlers/transcribe-media.js'),
  'transcribe-post': () => import('./_handlers/transcribe-post.js'),
  'transcribe-post-get': () => import('./_handlers/transcribe-post-get.js'),
  'twitter-feed': () => import('./_handlers/twitter-feed.js'),
  'twitter-oauth-callback': () => import('./_handlers/twitter-oauth-callback.js'),
  'twitter-oauth-start': () => import('./_handlers/twitter-oauth-start.js'),
  'twitter-post': () => import('./_handlers/twitter-post.js'),
  'twitter-reply': () => import('./_handlers/twitter-reply.js'),
  'unified-content-api': () => import('./_handlers/unified-content-api.js'),
  'update-newsletter-covers': () => import('./_handlers/update-newsletter-covers.js'),
  'validate-csv-import': () => import('./_handlers/validate-csv-import.js'),
  'validate-social-credentials': () => import('./_handlers/validate-social-credentials.js'),
  // 2026-05-17: 'viral-library' removido — unificado com biblioteca normal em 2026-05-08, handler nunca existiu.
  'viral-stats': () => import('./_handlers/viral-stats.js'),
  'x-manual-report': () => import('./_handlers/x-manual-report.js'),
  'youtube-search': () => import('./_handlers/youtube-search.js'),
};
